@baseUrl =  http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MjE4OTc2MS1lYTQzLTQ3MTItOGZhNC03ZDczMGU4YTJmNTYiLCJpYXQiOjE2OTY0NjM2Nzd9.phlxWXMfRh1QKWu3ROG-10tco2WhXp1gfSKVGT6v-D3mPuvQCfNtzz0dSFqOXj8BONlX2vunu1Gpx37EluxR3Cm9iKufcjZ3EqdNiVoXGTO4W-9tZ9GB9DzmQsjtiQJ1mBZR3MFe2aZWtoBJibP8hZP_0eW8Fn8N0ucQMBKPsWnutFRRotMBkG_BwdBu0cUBIs9QdmJxxLB1gNdpKtKPfh-zKU4Boebq4DrPhBt8GJxvgXnhz58ZJvk_ZfJlwSdESKsoEIvyFFpxfUvWW_w-w7TZjnuqSwNh3vd5RCg5oWCGDvt6gOdF-xxa-_0xswArN8e8UfBPxTCf3RG8pm05lQ
# @authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Francinilton",
  "email": "francinilton@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "francinilton@gmail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 7",
  "content": "Conteúdo da pergunta"
}

###

# @name fetch_recents_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
