@baseUrl =  http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MjE4OTc2MS1lYTQzLTQ3MTItOGZhNC03ZDczMGU4YTJmNTYiLCJpYXQiOjE3MDA5NTAxNTN9.o_OnidNQpwa2rLuRJeY6ediWGv7WhzUE_8xS9qwmsv1Y7VSv3k-1W2QYgHkjwEWEPzM4mbnA8p71nbMJ1oQJASIZnY1bWL7T-0TdS_h1EIADqhdX33lGCVGyThVwkJwQGgdbNozNAJVEe-QzxB3HHsoPMCSwFG2-K5bJFjVdDffMk969rdR1i53ZK_MHUkFU7Ua6Gm1iKe9MSwL_gJipOsetsMOP6Iu1xpPIAbIlKU9r_mqJqU4QaPro5jMvDCu0L1AWcu5sRRk-PYbNQGpQXP2lSPZ4Gi5DwXYN5Fc6ZMqLyxnEdLkxGbHzk0m--B26KMT5Uge9WZGGWHw7s8pKeg
# @authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jhon Doen da Silva",
  "email": "johndoe2@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "francinilton@gmail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 76",
  "content": "Conteúdo da pergunta"
}

###

# @name fetch_recents_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
